enum GraphConstants {
  SET_START_NODE = 'SET_START_NODE',
  SET_END_NODE = 'SET_END_NODE',
  SET_BRIDGE_NODE = 'SET_BRIDGE_NODE',
  RESET = 'RESET',
  DONE_RESETTING = 'DONE_RESETTING',
  SET_SUCCESS = 'SET_SUCCESS',
}

export default GraphConstants;
